_target_: rl.config.schemas.CarRacingEnvConfig
name: carracing
name_version: CarRacing-v3
render_mode: rgb_array
continuous: false
min_std: 0.15
init_std: 0.6
lap_complete_percent: 0.95
stack_frames: 4